name: auto-release
on:
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['16']
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node 16
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - run: git config --global user.email "jorge.mendez.ortega@gmail.com"
      - run: git config --global user.name "Jorge Mendez Ortega"
      - run: npm install
      - run: npm run release
      - run: git status
      - run: git log
      - run: ls -ls
      - run:     git push origin HEAD:${GITHUB_REF_NAME}
      - run: git push origin --follow-tags
